---
version: "3"

services:

  rmshelper:
    container_name: rmshelper
    build: .
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      STAGE:
    command: ["python", "handler.py"]