---
version: "3"

services:

  rmshelper:
    container_name: rmshelper
    build: .
    ports:
      - 5000:5000
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      STAGE:
      FLASK_APP: api.py
    command: ["flask", "run", "--host=0.0.0.0"]