service: rmshelper
plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.6
  stage: ${env:STAGE}
  region: ${env:AWS_REGION_NAME}
  apiKeys:
    - ${env:STAGE}-InternalAccess
  usagePlan:
    quota:
      limit: 3000
      period: MONTH
    throttle:
      burstlimit: 200
      ratelimit: 100s

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  include:
    - handler.py
    - rmshelper/**
  exclude:
    - ./**

functions:
  quick_invoice:
    handler: handler.quick_invoice
    events:
      - http:
          path: rms/quick_invoice/{opportunity_id}
          method: get
          private: true
